### ISSUE TITLE
scvi ignoring GPU because of jax

### ISSUE THREAD

**Issue by bio-la** [scverse/scvi-tools#2582] opened 2024-03-01 16:54 UTC
hey scvi team, 
one of our users reported that they need to explicitly install jax after installation of `scvi-tools 1.1.1` to ensure the GPU is visible. 
https://github.com/DendrouLab/panpipes/issues/204
can you recommend what packages and in which order I need to install them in the environment? 

thank you!

**Comment by canergen** [comment] 2024-03-01 17:02
Is our installation guide failing? https://docs.scvi-tools.org/en/stable/installation.html

**Comment by bio-la** [comment] 2024-03-01 17:12
The instructions are correct, but explicitly installing transitive dependencies (jax) that are already in the environment after installing scvi is the only way to fix the issue. is this behaviour expected?

**Comment by martinkim0** [comment] 2024-03-01 17:19
Hi @bio-la, thanks for bringing up this issue. This is expected behavior because, by default, our dependencies don't specify the CUDA build of JAX as a direct dependency since not everyone will be running JAX on GPUs. So if users want CUDA-enabled installations of JAX (and PyTorch!), they should ideally be installing these _before_ scvi-tools.

**Comment by bio-la** [comment] 2024-03-01 17:26
thanks for the clarification!

**Comment by martinkim0** [comment] 2024-03-02 00:54
I'll go ahead and close the issue if there's no additional questions

**Closed by martinkim0** 2024-03-02 00:54 UTC
Labels: bug
