### ISSUE TITLE
SCVI Does Not Use a Conditional VAE by Default

### ISSUE THREAD

**Issue by valentinwust** [scverse/scvi-tools#1632] opened 2022-08-09 21:04 UTC
As the title says, the model `SCVI` by default uses a normal VAE, conditioning on the batch label needs to be explicitly enforced by passing `encode_covariates=True` ( 3713894 changed the default behaviour of `VAE`, that may have been the issue). If you want I can write a minimal demonstration, but this behaviour should be apparent from the code of `VAE`:

```python
class VAE(BaseModuleClass):
...
encode_covariates: bool = False,
...
cat_list = [n_batch] + list([] if n_cats_per_cov is None else n_cats_per_cov)
encoder_cat_list = cat_list if encode_covariates else None
...
self.z_encoder = Encoder(
    n_input_encoder,
    n_latent,
    n_cat_list=encoder_cat_list,
...
```

The code explicitly says that this should implement the model from [Lopez18], and `SCVI` is used for batch correction in [the tutorial](https://docs.scvi-tools.org/en/stable/tutorials/notebooks/harmonization.html), so I would assume that this behaviour is a bug? The [tutorial for scVI with scArches](https://docs.scvi-tools.org/en/stable/tutorials/notebooks/scarches_scvi_tools.html) explicitly enforces this:

```python
arches_params = dict(
    use_layer_norm="both",
    use_batch_norm="none",
    encode_covariates=True,
    dropout_rate=0.2,
    n_layers=2,
)
```

`VAE` does not appear to be used by any other models, so changing the default behaviour should fix this.

**Comment by adamgayoso** [comment] 2022-08-10 06:50
So this is only half right. It is correct by default that the encoder does not see the covariates (i.e., is not conditional). However, the decoder does see the covariates (is conditional) always. 

This has always been the case for scVI (see [here](https://github.com/romain-lopez/scVI-reproducibility/blob/master/scVI.py) for the original implementation).

Also many models do indeed rely on this `VAE` class.

**Comment by valentinwust** [comment] 2022-08-10 08:22
> So this is only half right. It is correct by default that the encoder does not see the covariates (i.e., is not conditional). However, the decoder does see the covariates (is conditional) always.

True, I overlooked that.

> Also many models do indeed rely on this `VAE` class.

Yeah, I didn't put too much effort into that suggestion.

> This has always been the case for scVI (see [here](https://github.com/romain-lopez/scVI-reproducibility/blob/master/scVI.py) for the original implementation).

I agree that the implementation does that, but doesn't everything else suggest the opposite? Fig.1a in the paper clearly suggests that the batch is part of the encoder input, and the variational posterior is always written as conditioned on the batch label, even in the comments of the original implementation:

```python
def variational_distribution(self):
        """
        defines the variational distribution or inference network of the model
        q(z, l | x, s)
        """
```

**Comment by adamgayoso** [comment] 2022-08-10 18:48
> I agree that the implementation does that, but doesn't everything else suggest the opposite? Fig.1a in the paper clearly suggests that the batch is part of the encoder input, and the variational posterior is always written as conditioned on the batch label, even in the comments of the original implementation

I agree the figure is misleading given what's actually happening in the code. I should note in the case of scArches transfer learning, the condition weights are indeed encoded, which deviates from the default parameters.

In the user guide, [here](https://docs.scvi-tools.org/en/stable/user_guide/models/scvi.html#inference), we specifically mention:

```
It it important to note that by default, scVI only receives the expression data as input (i.e., not the observed cell-level covariates). Empirically, we have not seen much of a difference by having the encoder take as input the concatenation of these items...
```

I'm going to close this issue considering there is not actually a bug in the code. If you'd like to discuss further, we'd appreciate posting on our [forum](https://discourse.scvi-tools.org/)

**Closed by adamgayoso** 2022-08-10 18:48 UTC
Labels: bug

**Comment by Chengwei94** [comment] 2023-10-07 08:20
Hi there sorry to hijack the discussion. It seesm to me if we set encode_covariates to False, then transfer learning is trivial (just passing through the encoder). Have yall seen any difference in projecting this way vs using scarches, or am I misunderstanding the whole problem.

**Comment by martinkim0** [comment] 2023-10-19 18:38
@Chengwei94 You are correct in that with our current default `encode_covariates=False`, there will be no difference in the encoder when transfer learning with scArches. However, there is a difference in the decoder since it takes in one-hot encodings of batch assignments as well as additional categorical/continuous covariates. scArches modifies all layers that expect this categorical information and will extend it to account for new categories in transfer learning data.

**Comment by Chengwei94** [comment] 2023-10-20 01:11
Thanks for the replys! I don't see why the decoder matter in TL tasks. Just surprised that such an obvious comparison cannot be found anywhr
