### ISSUE TITLE
Installing scvi-tools with conda and with pip

### ISSUE THREAD

**Issue by Nasrine26** [scverse/scvi-tools#1551] opened 2022-06-02 13:04 UTC
Hi, I am trying to install scvi-tools with conda using conda install scvi-tools -c conda-forge
using python 3.8 and also tried with python 3.9

When I import scvi I get the following error:
`AttributeError: module 'distutils' has no attribute 'version'
`

I also tried installing scvi-tools with pip: `pip install scvi-tools` or `pip install scvi-tools[tutorials]`, but got the following error when I import scvi 

```
TypeError: Descriptors cannot not be created directly.
If this call came from a _pb2.py file, your generated code is out of date and must be regenerated with protoc >= 3.19.0.
If you cannot immediately regenerate your protos, some other possible workarounds are:
 1. Downgrade the protobuf package to 3.20.x or lower.
 2. Set PROTOCOL_BUFFERS_PYTHON_IMPLEMENTATION=python (but this will use pure-Python parsing and will be much slower).

More information: https://developers.google.com/protocol-buffers/docs/news/2022-05-06#python-updates
```

How can I install scvi? 

Many thanks

**Comment by dibidave** [comment] 2022-06-03 06:41
Worked like a charm, thank you!

**Comment by adamgayoso** [comment] 2022-06-03 10:06
@jjhong922 can you look into this?

**Comment by jjhong922** [comment] 2022-06-03 21:43
@adamgayoso This was a temporary issue caused by pytorch-lightning's protobuf dependency https://github.com/PyTorchLightning/pytorch-lightning/issues/13159. Safe to close this issue.

**Comment by jjhong922** [comment] 2022-06-03 21:43
Actually to make sure it never happens I'll pin our pytorch lightning version

**Closed by jjhong922** 2022-06-03 21:43 UTC
Labels: bug

**Comment by rimelof** [comment] 2022-06-06 22:44
Hi,

I am not very familiar with resolving conflicts, so I may be making some mistake.

I am having the same error, and `pip install --upgrade protobuf==3.20.0` didn't work. I then tried ` pip install 'pytorch-lightning>=1.6.4'`, resulting in
```
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
scvi-tools 0.16.3 requires pytorch-lightning<1.6,>=1.5, but you have pytorch-lightning 1.6.4 which is incompatible.
```

This happened  both when installing scvi via pip or via conda.

How can I install scvi?

**Comment by jjhong922** [comment] 2022-06-06 23:28
@rimelof  Hi there, we fixed this issue in a patch v0.16.3. You can run `pip install scvi-tools --upgrade` to fix the issue

**Comment by jjhong922** [comment] 2022-06-06 23:30
You shouldn't have to install a version of pytorch lightning separately. This seems to be whats causing your issue, since you effectively pinned it at 1.6.4 when you installed it with an explicit version.

**Comment by rimelof** [comment] 2022-06-07 01:59
Started a clean environment and installed 0.16.3 with pip. It works now. Thanks!
