### ISSUE TITLE
Error in model training

### ISSUE THREAD

**Issue by swasthadinakar** [scverse/scvi-tools#2909] opened 2024-07-24 19:31 UTC
When I train my MULTIVI model on fully paired data, I am getting this error:

ValueError: Expected parameter loc (Tensor of shape (128, 18)) of distribution Normal(loc: torch.Size([128, 18]), scale: torch.Size([128, 18])) to satisfy the constraint Real(), but found invalid values:
tensor([[nan, nan, nan,  ..., nan, nan, nan],
        [nan, nan, nan,  ..., nan, nan, nan],
        [nan, nan, nan,  ..., nan, nan, nan],
        ...,
        [nan, nan, nan,  ..., nan, nan, nan],
        [nan, nan, nan,  ..., nan, nan, nan],
        [nan, nan, nan,  ..., nan, nan, nan]], grad_fn=<AddmmBackward0>)
        
        
I did not provide a batch_key for scvi.model.MULTIVI.setup_anndata as my entire dataset was paired and could not be separated into batches based on modality. 

I have used the 10x PBMC multiome dataset for my work: https://www.10xgenomics.com/datasets/pbmc-from-a-healthy-donor-granulocytes-removed-through-cell-sorting-10-k-1-standard-1-0-0

How do I resolve this error?

**Comment by canergen** [comment] 2024-07-24 19:34
Hi. This is likely a duplicate of: https://github.com/scverse/scvi-tools/issues/2581#issuecomment-2019574427. Please follow the advices there. The fix is planned to be released with version 1.2

**Comment by canergen** [comment] 2024-07-26 04:53
Fixed in #2914, for now you can set `adversarial_mixing` in train to False.

**Closed by canergen** 2024-07-26 04:53 UTC
